### ISSUE TITLE
Wrap text correctly (don't break-word) on pre tags in log view

### ISSUE THREAD

**Issue by kparal** [fedora-infra/mote#62]
I'm reading one of the logs [1] and all the long lines are character-wrapped in the middle of the word. That's very uncomfortable to read. Please use word wrapping instead, wrapping at a whitespace.

Thanks!

[1] https://meetbot.fedoraproject.org/fedora-meeting/2015-08-26/fesco.2015-08-26-18.06.log.html/

**Comment by Cydrobolt** [comment]
Hmm. We are currently using `white-space: wrap;` on `.logdisplay pre`, which should wrap the text the same way `meetbot-raw` wraps it. Will investigate why it's breaking words in its wrapping.

**Comment by jwflory** [comment]
_Discussed in [2020-10-25 meeting](https://youtu.be/gpLPDgYRIvA)_.

---

@ramyaparimi is going to take on this task to get more familiar with the codebase. For now, we are waiting on more explicit developer environment instructions (see #126). This issue is in scope for the end of the current sprint on Sunday, 8 November 2020.

**Comment by ramyaparimi** [comment]
I was trying to look at the link provided above..it gave me 404. So I went and browsed for the link in meetbot logs and found this.
https://meetbot-raw.fedoraproject.org/teams/fesco/fesco.2015-08-26-18.06.log.html

All the long lines seem to be breaking properly at white spaces and no words are broken. 

I also compared css styles for both`meetbot-raw`  and `mote`  and both are using `whitespace: pre-wrap`.

Can some please let me know what the issue is?

**Comment by kparal** [comment]
Here you go:
https://meetbot.fedoraproject.org/teams/f33-final-go_no_go-meeting/f33-final-go_no_go-meeting.2020-10-22-17.00.log.html

**Comment by ramyaparimi** [comment]
Oh I see the issue in this page ! Thank you for sharing!

**Comment by ramyaparimi** [comment]
Created [PR#147](https://github.com/fedora-infra/mote/pull/147) to address the issue.

**Comment by ramyaparimi** [comment]
Closing this issue as (PR#147)[https://github.com/fedora-infra/mote/pull/147] has been merged. 🎉 
@nasirhm Thank you for merging my first PR 😄  🎉
