### ISSUE TITLE
Links to some Meetbot meetings broken (unless you use meetbot-raw)

### ISSUE THREAD

**Issue by jflory7** [fedora-infra/mote#83]
Today, we noticed that some meetings cannot be viewed from the regular way in Meetbot. You can see the meeting for the day, but when you open it, it reports that it was unable to open the page (also citing a different address from the one in the URL bar). However, if you view the logs from `meetbot-raw`, you are able to view them.

See the following examples.

* [Original Summary](https://meetbot.fedoraproject.org/fedora-ambassadors/2016-02-07/ambassadors_-_emea_-_devconf.cz.2016-02-07-16.30.html)
* [Meetings by date](https://meetbot.fedoraproject.org/fedora-ambassadors/2016-02-07/)
* **Error**: "The requested URL /meetbot/teams/ambassadors_-_emea_-_devconf.cz/ambassadors_-_emea_-_devconf.cz.2016-02-07-16.30.log.html was not found on this server."

**Comment by cydrobolt** [comment]
The team categorisation script only runs in meetings ran in #fedora-meeting. Hence,  your meeting in the ambassadors channel isn't placed in the team folder or available to view (because mote thinks that it is part of a team, due to #meetingname being used.) 

 We should revamp the get meeting logs API endpoint to fetch directly from the channel rather than the team
