### ISSUE TITLE
RFE: Add link previews to meeting summaries

### ISSUE THREAD

**Issue by jwflory** [fedora-infra/mote#95]
`#link` is a Meetbot command to add a link to the Meetbot minutes. It would be a cool and useful feature if linked URLs had a preview below the link before you open it. For an image, this could be a small thumbnail of the image in the logs. For a Trac ticket, it could be a thumbnail of the page contents, similar to how when you post a link in something like Facebook or other social media platforms.

**Comment by cydrobolt** [comment]
I'm not sure if implementing this would be a sound decision given the scope of our project.

In order to have a feature of the sort, we would have to make a ton of requests to arbitrary web servers without a means to verify their legitimacy. This could a door for abuse. People who want to see a page could click on it or look it up elsewhere. Is it really critical to have a thumbnail show up underneath?

**Comment by jflory7** [comment]
It's obviously not critical, but it could be an interesting feature to add in. There seem to be secure ways to do this, particularly if the hyperlink links to a site that generates that kind of information. Ideally, it would be similar to posting a link in WordPress, Facebook, Telegram, etc.

This obviously isn't mission critical, but it would be nice "extra" feature. I'll defer judgment to those who know better than me. :)

**Comment by cydrobolt** [comment]
Right -- WordPress's feature is limited to authors and admins. Telegram might have the resources to do this or uses your own connection to fetch the page. 

Personally, I don't see the benefits outweighing the risks in this case. I'd like to see other opinions as well.

**Comment by jwflory** [comment]
Four years later, I concur with what @cydrobolt originally told me. :grinning: So I am going to close this out as `wontfix`.
